# Generated by Django 5.2.15 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('car_type', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('license_image', models.ImageField(upload_to='licenses/')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
