# Generated by Django 5.2.15 on 2026-06-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_image',
        ),
        migrations.CreateModel(
            name='LicenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='licenses/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_images', to='garage.car')),
            ],
        ),
    ]
