# Generated by Django 5.2.15 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_remove_car_car_image_remove_car_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
